def menu_inicial():
  print("=" * 50)
  print()
  print("-" * 50)
  print("SISTEMA DA ENGINSTOCK:")
  print("-" * 50)
  print()
  print("1 - Gerenciar Estoque.")
  print("2 - Controle de Estoque.")
  print("3 - Encerrar Sistema.")
  print()
  print("=" * 50)

def menu_gerenciar_estoque():

    print("=" * 50)
    print()
    print("-" * 50)
    print("GERENCIAR ESTOQUE:")
    print("-" * 50)
    print()
    print("1 - Adicionar novo produto do estoque.")
    print("2 - Remover produto do estoque.")
    print("3 - Voltar.")
    print("4 - Encerrar Sistema.")
    print()
    print("=" * 50)

def menu_controle_estoque():

    print("=" * 50)
    print()
    print("-" * 50)
    print("CONTROLE ESTOQUE:")
    print("-" * 50)
    print()
    print("1 - Adicionar quantidade de um produto.")
    print("2 - Remover quantidade de um produto.")
    print("3 - Voltar.")
    print("4 - Encerrar Sistema.")
    print()
    print("=" * 50)